name: LPHK-build
channels:
  - defaults
dependencies:
  - python=3.7*
  - pip
  - tk
  - pip:
    - git+git://github.com/FMMT666/launchpad.py.git@3e3fc3b2589d9ced80bc6c9b218dd90c8a2dd485
    - pillow
    - pygame
    - pynput
    - tkcolorpicker
    - https://github.com/pyinstaller/pyinstaller/archive/develop.zip
    - py-getch
    - pyautogui
