name: LPHK
channels:
  - defaults
dependencies:
  - python=3.7*
  - pip
  - tk
  - pip:
#    - launchpad-py
    # custom version for MK3 support
    - "--editable=git+git://github.com/FMMT666/launchpad.py.git@3e3fc3b2589d9ced80bc6c9b218dd90c8a2dd485"
    - pillow
    - pygame
    - pynput
    - tkcolorpicker
    - py-getch
    - pyautogui
